import type { ReasonCode } from './types.js';

export const REASON_CODE_SENTENCES: Record<ReasonCode, string> = {
  VAL_SCHEMA_INVALID: 'Your application could not be processed because required information was missing or invalid.',
  VAL_SEGMENT_PRODUCT_MISMATCH: 'The loan product requested does not match your applicant category.',
  BUR_LIVE_OVERDUE: 'You have a live overdue amount on an existing loan or credit account.',
  BUR_RECENT_SEVERE_DELINQ: 'A serious payment delay (90+ days) was recorded on your credit report in the last 12 months.',
  BUR_SUIT_FILED: 'A legal suit related to a credit obligation has been filed against you.',
  BUR_SETTLEMENT: 'A loan settlement was recorded on your credit report in the last 24 months.',
  BUR_ENQUIRY_VELOCITY: 'You have applied for credit with a large number of different lenders recently.',
  BUR_THIN_FILE: 'Your credit history is too limited for us to assess.',
  CAP_FOIR_EXCEEDED: 'Your existing obligations relative to your income are higher than we can approve for this loan.',
  AGE_TENURE_MISMATCH: 'The requested loan tenure would extend past the maximum eligible age.',
  EMP_INSUFFICIENT_VINTAGE: 'Your current employment tenure is shorter than the minimum we require.',
  BIZ_INSUFFICIENT_VINTAGE: 'Your business registration is more recent than the minimum we require.',
  POL_AMOUNT_REDUCED: 'Your approved amount was reduced based on your verified income and risk grade.',
  POL_BELOW_MIN_TICKET: 'The amount you are eligible for falls below the minimum loan size we offer.',
  bureau_score: 'Your credit bureau score.',
  utilization_level: 'How much of your available credit you are currently using.',
  utilization_trend: 'The recent trend in your credit utilization.',
  foir: 'Your obligations relative to your verified income.',
  insufficient_funds_bounces: 'Payments returned due to insufficient funds in your bank account.',
  delinquency_recency: 'Recent history of late payments on your accounts.',
  credit_history_age: 'The length of your credit history.',
  enquiry_per_lender: 'How often you have applied for credit relative to the number of lenders.',
  epfo_vintage: 'The length of your current employment, as verified through EPFO.',
  employer_category: 'The category of your employer.',
  salary_stability: 'The consistency of your monthly salary credits.',
  gst_filing_punctuality: 'The punctuality of your business's GST filings.',
  business_vintage: 'The length of time your business has been registered.',
  business_inflow_volatility: 'The consistency of your business's banking inflows.',
};
